services:
  - type: web
    name: nipa-birthday-website
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1