services:
  - type: web
    name: nipa-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000
    healthCheckPath: /
    disk:
      name: nipa-disk
      mountPath: /opt/render/project/src
      sizeGB: 1
    autoDeploy: true
    branch: main
    rootDir: .
    region: oregon
    scaling:
      minInstances: 1
      maxInstances: 1